#pragma once

namespace G
{
	bool headbo;
	bool Neckbo;
	bool Chestbo;
	bool Pelvisbo;
	float aimbot_smooth;
	float aimbot_fov;
	float aimbot_max_distance;
	bool Silenta;
	bool EspWeapon = true;
	bool RefreshEach1s = true;
	bool Snaplines = false;
	bool CornerBox = true;
	float CornerBoxThicc = 1.7f;
	float RedDistance = 40.0f;
	float CornerBoxScale = 0.20;
	bool PunktierSnaplines = true;
	float PunktierPower = 16.6f;
	bool SnaplinesIn50m = false;
	bool Baim = true;
	float SkeletonThicc = 1.0f;
	float PlayerBoxThicc = 3.0f;
	bool WeakSpotAimbot = true;
	bool ProjectileTpEnable = true;
	bool ShowTimeConsumed = true;
	float Smooth = 0.3;
	bool CollisionDisableOnAimbotKey = true;
	bool FlyingCars = false;
	bool UseEngineW2S = true;
	bool Chests = true;
	bool TpPrisonersEnable = true;
	bool DrawSelf = true;
	bool LootWeapons = true;
	int JumpScale = 1;
	bool Projectiles = true;
	int TpTimeInterval = 250;
	float LootTier = 1;
	bool LootMelee = true;
	bool bAllowedTp = true;
	bool Outline = true;
	bool Skeletons = true;
	bool EspPlayerName = true;
	bool EspLoot = true;
	bool EspRifts = false;
	bool EspSupplyDrops = false;
	bool EspTraps = false;
	bool EspVehicles = false;
	bool Healthbars = true;
	bool LootHeals = true;
	bool LootAttachments = true;
	bool LootAmmo = true;
	bool EspBox = true;
	bool LootEquipment = true;
	bool TpLootAndCorpses = true;
	bool TpZombiesEnable = true;
	bool EnableHack = true;
	bool LootFood = true;
	bool LootWear = true;
	bool TpAnimalsEnable = true;
	bool TpSentriesEnable = true;
	bool TimeSpeedhackEnable = false;
	bool MovSpeedhackEnable = true;
	int MovSpeedhackScale = 2;
	bool AimbotEnable = true;
	bool EspSentries = true;
	bool EspZombies = false;
	bool EspPlayers = true;
	bool EspCorpses = true;
	bool EspAnimals = true;
	bool EspDrones = true;
	float RenderDist = 200;
	float ChestsRdist = 200;
	bool AimbotTargetPlayers = true;
	bool AimbotTargetZombies;
	float LootRenderDist = 200;
	int IconScale = 21;
	bool LootEnable = false;
	bool AimbotTargetDrones;
	bool OnlyWeapons = true;
	bool AimbotTargetAnimals;
	bool AimbotTargetSentries;
	int ItemRarityLevel = 7;
	bool NoRecoil = true;
	bool InfAmmo = true;
}

